blog/urls.py
from django.urls import path
from .views import index

app_name = "blog"

urlpatterns = [
    path('blog', index, name='list')
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('article.urls', namespace='list')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, tag_create, tag_list,\
    tag_detail, tag_delete, tag_update, ing_create, ing_update, ing_delete


app_name = 'recipes'

urlpatterns = [
    path('list/', recipe_list, name='list'),
    path('detail/<slug:slug>/', recipe_detail, name='detail'),
    path('create/', recipe_create, name='create'),
    path('update/<slug:slug>/', recipe_update, name='update'),
    path('delete/<slug:slug>/', recipe_delete, name='delete'),

    path('tag/list/', tag_list, name='tag_list'),
    path('tag/create/', tag_create, name='tag_create'),
    path('tag/detail/<int:pk>/', tag_detail, name='tag_detail'),
    path('tag/delete/<int:pk>/', tag_delete, name='tag_delete'),
    path('tag/update/<int:pk>/', tag_update, name='tag_update'),

    path('<slug:recipe_slug>/ing/create', ing_create, name='ing_create'),
    path('<slug:recipe_slug>/ing/update/<int:pk>/', ing_update, name='ing_update'),
    path('<slug:recipe_slug>/ing/delete/<int:pk>/', ing_delete, name='ing_delete'),


]

recipes/models.py
import random
import string

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.text import slugify


class Tag(models.Model):
    title = models.CharField(max_length=228)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=228, db_index=True)
    slug = models.SlugField(null=True, unique=True)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    UNIT = (
        (0, 'GRAM'),
        (1, 'MILLILITR'),
        (2, 'DONA'),
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    title = models.CharField(max_length=228)
    quantity = models.IntegerField()
    unit = models.IntegerField(choices=UNIT)
    created_date = models.DateTimeField(auto_now=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    def get_author(self):
        return self.recipe.author

    def __str__(self):
        return self.title


def recipe_post_save(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None:
            instance.slug = slugify(instance.title)
        try:
            instance.save()
        except Exception as e:
            rand = "".join(random.choice(string.ascii_lowercase) for _ in range(4))
            instance.slug = slugify(instance.title) + f"-{rand}"
            instance.save()


post_save.connect(recipe_post_save, sender=Recipe)

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, reverse
from recipes.models import Recipe, Tag, RecipeIngredient
from .form import RecipeCreateForm, RecipeUpdateForm, TagForm, RecipeIngredientForm
from django.contrib import messages


# recipe ----------------------------------------------------------------------------------------------------------------
def recipe_list(request):
    recipes = Recipe.objects.filter(is_active=True).order_by('-id')
    q = request.GET.get('q')
    if q:
        recipes = recipes.filter(title__icontains=q)
    context = {
        'object_list': recipes
    }
    return render(request, 'recipe/list.html', context)


def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    context = {
        'object': recipe
    }
    return render(request, 'recipe/detail.html', context)


@login_required
def recipe_create(request, *args, **kwargs):
    form = RecipeCreateForm()
    if request.method == "POST":
        form = RecipeCreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.is_active = True
            obj.save()
            form.save_m2m()
            return redirect(reverse('recipes:detail', kwargs={'slug': obj.slug}))
            # return redirect('recipes:list')
    context = {
        'form': form
    }
    return render(request, 'recipe/create.html', context)


@login_required
def recipe_update(request, slug):
    obj = get_object_or_404(Recipe, slug=slug)
    form = RecipeUpdateForm(instance=obj)
    if request.method == 'POST':
        form = RecipeUpdateForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:detail', kwargs={'slug': obj.slug}))
    context = {
        'form': form
    }
    return render(request, 'recipe/update.html', context)


@login_required
def recipe_delete(request, slug):
    obj = get_object_or_404(Recipe, slug=slug)
    if request.method == "POST":
        obj.delete()
        messages.error(request, f"{obj.title} o'chirildi")
        return redirect('recipes:list')
    context = {
        'object': obj
    }
    return render(request, 'recipe/delete.html', context)


# tag ----------------------------------------------------------------------------------------------------------------
def tag_list(request):
    tags = Tag.objects.order_by('-id')
    q = request.GET.get('q')
    if q:
        tags = tags.filter(title__icontains=q)
    context = {
        'object_list': tags
    }
    return render(request, 'recipe/tag/list.html', context)


def tag_detail(request, pk):
    tag = get_object_or_404(Tag, id=pk)
    context = {
        'object': tag
    }
    return render(request, 'recipe/tag/detail.html', context)


@login_required
def tag_create(request, *args, **kwargs):
    form = TagForm()
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return redirect(reverse('recipes:tag_detail', kwargs={'pk': obj.id}))
            # return redirect('recipes:list')
    context = {
        'form': form
    }
    return render(request, 'recipe/tag/create.html', context)


@login_required
def tag_update(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    form = TagForm(instance=obj)
    if request.method == 'POST':
        form = TagForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:tag_detail', kwargs={'pk': obj.id}))
    context = {
        'form': form
    }
    return render(request, 'recipe/tag/update.html', context)


@login_required
def tag_delete(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    if request.method == "POST":
        obj.delete()
        messages.error(request, f"{obj.title} o'chirildi")
        return redirect('recipes:tag_list')
    context = {
        'object': obj
    }
    return render(request, 'recipe/tag/delete.html', context)


# ing ----------------------------------------------------------------------------------------------------------------
@login_required
def ing_update(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    form = RecipeIngredientForm(instance=obj)
    if request.method == 'POST':
        form = RecipeIngredientForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:detail', kwargs={'slug': recipe.slug}))
    context = {
        'form': form
    }
    return render(request, 'recipe/ing/update.html', context)


@login_required
def ing_delete(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.method == "POST":
        obj.delete()
        messages.error(request, f"{obj.title} o'chirildi")
        return redirect(reverse('recipes:detail', kwargs={'slug': recipe.slug}))
    context = {
        'object': obj
    }
    return render(request, 'recipe/ing/delete.html', context)


@login_required
def ing_create(request, recipe_slug, *args, **kwargs):
    form = RecipeIngredientForm()
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.method == "POST":
        form = RecipeIngredientForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.recipe = recipe
            obj.save()
            return redirect(reverse('recipes:detail', kwargs={'slug': recipe.slug}))
    context = {
        'form': form
    }
    return render(request, 'recipe/ing/create.html', context)

templates/recipe/create.html
{% extends 'base.html' %}

{% block title %} Recipe Create {% endblock %}

{% block content %}

<form method="post">
  {% csrf_token %}
    <div class="rec_title">
    <label for="id_title">Title</label>
    {{form.title}}
    </div>
    <div class="rec_title">
    <label for="id_tags">Tags</label>
    {{form.tags}}
    </div>
  <button type="submit" class="btn" style="color: green">Submit</button>
</form>

{% endblock %}

templates/recipe/delete.html
{% extends 'base.html' %}

{% block title %} Recipe Create {% endblock %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        <div>
            Rostan ham siz {{object.title}}ni o'chirmoqchimisz
        </div>
        <a href="{% url 'recipes:detail' obj ect.slug %}">YOQ</a>
        <button type="submit" class="btn" style="color: green">HA</button>
    </form>
</div>


{% endblock %}

templates/recipe/detail.html
{% extends 'base.html' %}

{% block title %} Recipe Detail {% endblock %}

{% block content %}
<div>
    <a class="btn" href="{% url 'recipes:list' %}" style="color: #000000">back to Recipe list</a>
    <a class="btn" href="{% url 'recipes:ing_create' object.slug %}" style="color: #000000">Add Ingredient</a>
</div>
  <div class="rec_list">
    <h1>{{ object.title }}</h1>
    <p>{{ object.author }}</p>
    <div>
      {% for tag in object.tags.all %}
      <button class="tags">{{tag.title }}</button>
      {% endfor %}
    </div>
    <a class="btn" href="{% url 'recipes:update' object.slug %}" style="color: #000000">Edit</a>
    <a class="btn" href="{% url 'recipes:delete' object.slug %}" style=" color: red">Delete</a>
    <div class="ingredient_ram">
      {{object.created_date}}
    </div>
  </div>
<div>
  {% for ingredient in object.ingredients.all %}

  <div class="rec_lists">
    <h2>{{ingredient.title }}</h2>
    <p>{{ingredient.quantity}} - {{ingredient.get_unit_display.lower}}</p>
    <a class="btn" href="{% url 'recipes:ing_update' ingredient.recipe.slug ingredient.id %}" style="color: #000000">Edit</a>
    <a class="btn" href="{% url 'recipes:ing_delete' ingredient.recipe.slug ingredient.id %}" style="color: red">Delete</a>
    <div class="ingredient_ram">
      {{ingredient.created_date}}
    </div>
  </div>

  {% endfor %}
</div>


{% endblock %}

templates/recipe/list.html
{% extends 'base.html' %}

{% block title %} Recipe List {% endblock %}

{% block content %}
<div>
    <a href="{% url 'recipes:create' %}">Add New Recipe</a>
        <form action="{% url 'recipes:list' %}">
         <input class="search" type="search" name="q" placeholder="search..." autocomplete="off">
         <input style="color: green" type="submit" value="search" >
        </form>
</div>
<ol>
        {% for object in object_list %}
            <li class="recipe_list">
               <div>
                   <a href="{% url 'recipes:detail' object.slug %}">{{object.title}}</a>
               </div>
                  {{object.author}}
                  <span>{{object.ingredients.count}}</span>
            </li>
        {% endfor %}
</ol>


{% endblock %}

templates/recipe/update.html
{% extends 'base.html' %}

{% block title %} Recipe Update {% endblock %}

{% block content %}

<form method="post">
  {% csrf_token %}
    <div class="rec_title">
    <label for="id_title">Title</label>
    {{form.title}}
    </div>
    <div class="rec_title">
    <label for="is_active">Is_Active</label>
    {{form.is_active}}
    </div>
    <div class="rec_title">
    <label for="id_tags">Tags</label>
    {{form.tags}}
    </div>
  <button type="submit" class="btn" style="color: green">Submit</button>
</form>

{% endblock %}