account/urls.py
from django.urls import path
from .views import login_views, logout_views, register_views


app_name = 'account'


urlpatterns = [
    path('login/', login_views, name='login'),
    path('logout/', logout_views, name='logout'),
    path('register/', register_views, name='register'),
]

article/urls.py
from django.urls import path
from .views import index, detail, create, newcreate, edit, delete, new_index

app_name = 'article'

urlpatterns = [
    path('', index, name='list'),
    path('article/detail/<slug:slug>/', detail, name='detail'),
    path('article/create/', create, name='create'),
    path('article/newcreate/', newcreate, name='newcreate'),
    path('article/edit/<slug:slug>/', edit, name='edit'),
    path('article/d/delete/<slug:slug>/', delete, name='delete'),
    path('new_edit/', new_index, name='new_index'),
]

blog/urls.py
from django.urls import path
from .views import index

app_name = "blog"

urlpatterns = [
    path('blog', index, name='list')
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('article.urls', namespace='list')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, tag_create, tag_list,\
    tag_detail, tag_delete, tag_update, ing_create, ing_update, ing_delete


app_name = 'recipes'

urlpatterns = [
    path('list/', recipe_list, name='list'),
    path('detail/<slug:slug>/', recipe_detail, name='detail'),
    path('create/', recipe_create, name='create'),
    path('update/<slug:slug>/', recipe_update, name='update'),
    path('delete/<slug:slug>/', recipe_delete, name='delete'),

    path('tag/list/', tag_list, name='tag_list'),
    path('tag/create/', tag_create, name='tag_create'),
    path('tag/detail/<int:pk>/', tag_detail, name='tag_detail'),
    path('tag/delete/<int:pk>/', tag_delete, name='tag_delete'),
    path('tag/update/<int:pk>/', tag_update, name='tag_update'),

    path('<slug:recipe_slug>/ing/create', ing_create, name='ing_create'),
    path('<slug:recipe_slug>/ing/update/<int:pk>/', ing_update, name='ing_update'),
    path('<slug:recipe_slug>/ing/delete/<int:pk>/', ing_delete, name='ing_delete'),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Try Django {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

{% include "nav.html" %}
{% for message in messages %}
<p>{{message}}</p>
{% endfor %}
<hr>
<body>

{% block content %}


{% endblock %}

</body>
<hr>
{% include "footer.html" %}

</html>

templates/footer.html
<div>
    <p>
        <h2>footer</h2>
    </p>
</div>

templates/nav.html
{% load static %}

<div>
    <ul class="nav_link">
        <li>
            <a href="{% url 'article:list' %}">
            <img src="{% static 'image/img_1.png' %}" alt="">
            </a>
        </li>
        <li>
            <a href="{% url 'article:list' %}">Article</a>
        </li>
        <li>
            <a href="{% url 'blog:list' %}">Blogs</a>
        </li>
<!--        <li>-->
<!--            <a href="{% url 'recipes:list' %}">Recipes</a>-->
<!--            <ul>-->
<!--                <li><a href="#">Recipe</a></li>-->
<!--                <li><a href="#">Tag</a></li>-->
<!--            </ul>-->
<!--        </li>-->
        <div class="dropdown">
         <a href="#" class="drop">Recipes</a>
         <div class="dropdown-content">
             <a href="{% url 'recipes:list' %}">Recipe</a>
             <a href="{% url 'recipes:tag_list' %}">Tags </a>
         </div>
        </div>
    </ul>
</div>
<div>
    {% if request.user.is_authenticated %}
    {{request.user}}
    <span>
        <a href="{% url 'account:logout' %}">Logout</a>
    </span>
    {% else %}
    <span>
<!--        {{request.user}}-->
        <a href="{% url 'account:login' %}">Login</a>
    </span>
    {% endif %}
</div>