article/urls.py
from django.urls import path
from .views import index, detail, create, newcreate, edit, delete, new_index

app_name = 'article'

urlpatterns = [
    path('', index, name='list'),
    path('article/detail/<slug:slug>/', detail, name='detail'),
    path('article/create/', create, name='create'),
    path('article/newcreate/', newcreate, name='newcreate'),
    path('article/edit/<slug:slug>/', edit, name='edit'),
    path('article/d/delete/<slug:slug>/', delete, name='delete'),
    path('new_edit/', new_index, name='new_index'),
]

blog/urls.py
from django.urls import path
from .views import index

app_name = "blog"

urlpatterns = [
    path('blog', index, name='list')
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('article.urls', namespace='list')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
import random
import string

from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save


class Article(models.Model):
    title = models.CharField(max_length=228, db_index=True)
    image = models.ImageField(upload_to='articles', blank=True, null=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    content = models.TextField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.title} ({self.id})'

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     if self.slug is None:
    #         self.slug = slugify(self.title)
    #
    #     try:
    #         super().save()
    #     except Exception as e:
    #         rand = "".join(random.choice(string.ascii_lowercase) for _ in range(4))
    #         self.slug = slugify(self.title) + f"-{rand}"
    #         super().save()


# def article_pre_save(sender, instance, *args, **kwargs):
#     if instance.slug is None:
#         instance.slug = slugify(instance.title)


# def article_post_save(sender, instance, created, *args, **kwargs):
#     if created:
#         instance.slug = slugify(instance.title)
#         instance.save()


# post_save.connect(article_post_save, sender=Article)
# pre_save.connect(article_pre_save, sender=Article)

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

article/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponse, Http404, redirect, reverse
from .models import Article
from .forms import ArticleForm
import random
from django.contrib import messages


def _index(request):
    _id = random.randint(1, 4)
    article = Article.objects.get(id=_id)
    title = article.title
    content = article.content
    HTML_Content = f"""
    <h1>{title} (id:{article.id})<h1>
    <p>{content}<p>
"""
    return HttpResponse(HTML_Content)


def index(request):
    articles = Article.objects.filter(is_deleted__exact=False)
    q = request.GET.get('q')
    if q is not None:
        articles = articles.filter(title__icontains=q)
    return render(request, 'article/index.html', {'object_list': articles})


def detail(request, slug):
    if slug:
        article = Article.objects.get(slug=slug)
        context = {
            'object': article
        }
        return render(request, 'article/detail.html', context)
    return Http404


def create_1(request):
    context = {
        'created': False
    }
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article.objects.create(title=title, content=content)
        context['object'] = article
        context['created'] = True
    return render(request, 'article/create.html', context)


def create_2(request):
    form = ArticleForm
    context = {
        'form': form
    }
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Mr.{request.user} siz Muvaffaqiyatli Kirdingiz')
            context['object'] = form.data
            context['created'] = True
    return render(request, 'article/create.html', context)


@login_required
def create(request):
    form = ArticleForm(request.POST or None, files=request.FILES)
    if form.is_valid():
        form.save()
        messages.success(request, f'Mr.{request.user} siz Muvaffaqiyatli Article Yaratdingiz')
        return redirect('article:list')
    context = {
        'form': form
    }
    return render(request, 'article/create.html', context)


def newcreate_1(request):
    context = {

    }
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article.objects.create(title=title, content=content)
        context['object'] = article
        return redirect('article:list')
    return render(request, 'article/NewCreate.html', context)


def newcreate_2(request):
    form = ArticleForm
    context = {
        'form': form
    }
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            context['object'] = form.data
            context['created'] = True
            return redirect('article:list')

    return render(request, 'article/NewCreate.html', context)


@login_required
def newcreate(request):
    form = ArticleForm(request.POST or None, files=request.FILES)
    if form.is_valid():
        form.save()
        messages.success(request, f'Mr.{request.user} siz Muvaffaqiyatli Yangiz Article Yaratdingiz')
        return redirect('article:list')
    context = {
        'form': form
    }
    return render(request, 'article/NewCreate.html', context)


def edit_1(request, pk):
    article = Article.objects.get(id=pk)
    form = ArticleForm(instance=article)
    if request.method == "POST":
        form = ArticleForm(data=request.POST, instance=article)
        form.save()
        return redirect(reverse('article:detail', kwargs={'pk': article.id}))
    ctx = {
        'form': form
    }
    return render(request, "article/edit.html", ctx)


def edit_2(request, pk):
    article = Article.objects.get(id=pk)
    form = ArticleForm(instance=article)
    if request.method == "POST":
        form = ArticleForm(data=request.POST, instance=article)
        form.save()
        return redirect(reverse('article:detail', kwargs={'pk': article.id}))

    ctx = {
        'form': form
    }
    return render(request, 'article/edit.html', ctx)


def delete_1(request, pk):
    article = Article.objects.get(id=pk)
    if request.method == "POST":
        article.delete()
        return redirect('article:list')
    ctx = {
        'object': article
    }
    return render(request, 'article/delete.html', ctx)


def edit_3(request, pk):
    article = Article.objects.get(id=pk)
    form = ArticleForm(instance=article)
    if request.method == "POST":
        form = ArticleForm(data=request.POST, instance=article)
        form.save()
        return redirect(reverse('article:detail', kwargs={'pk': article.id}))
    ctx = {
        'form': form
    }
    return render(request, 'article/edit.html', ctx)


@login_required
def delete(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == "POST":
        # article.delete()
        article.is_deleted = True
        article.save()
        return redirect('article:list')
    context = {
        'object': article
    }
    return render(request, 'article/delete.html', context)


@login_required
def edit(request, slug):
    article = Article.objects.get(slug=slug)
    form = ArticleForm(instance=article)
    if request.method == "POST":
        form = ArticleForm(data=request.POST, instance=article, files=request.FILES)
        form.save()
        messages.success(request, f"Mr.{request.user} siz Muvaffaqiyatli O'zgarishni Amalga Oshirdingiz")
        return redirect(reverse('article:detail', kwargs={'slug': article.slug}))
    context = {
        'form': form
    }
    return render(request, 'article/edit.html', context)


@login_required
def delete_2(request, pk):
    article = Article.objects.get(id=pk)
    if request.method == "POST":
        article.is_deleted = True
        article.save()
        messages.success(request, f"Mr.{request.user} siz Muvaffaqiyatli O'chirdingiz")
        return redirect('article:list')
    context = {
        'object': article
    }
    return render(request, 'article/delete.html', context)


def new_index(request):
    articles = Article.objects.filter(is_deleted=False).order_by('-slug')
    q = request.GET.get('q')
    if q is not None:
        articles = articles.filter(title__icontains=q)
    return render(request, 'article/newedit.html', {'object_list': articles})

templates/article/NewCreate.html
{% extends 'base.html' %}

{% block title %}New Create{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
<!--    <div>-->
<!--        <label for="title">Title</label>-->
<!--        <br>-->
<!--        <input type="text" id="title" placeholder="title" name="title">-->
<!--    </div>-->

<!--    <div>-->
<!--        <label for="content">Content</label>-->
<!--        <br>-->
<!--        <textarea name="content" id="content" cols="50" rows="4" placeholder="content"></textarea>-->
<!--    </div>-->

            {{form.as_p}}
        <div style="margin-top: 20px">
            <input type='submit' value="Add NEW NEW" class="btn">
        </div>

</form>

{% endblock %}

templates/article/create.html
{% extends 'base.html' %}

{% block title %}Create Article{% endblock %}

{% block content %}
    {% if created %}
        <h1>{{object.title}}</h1>
        <p>{{object.content}}</p>
        <p>
            <code>
                {{object.created_date}}
            </code>
        </p>
    {% else %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

<!--    <div>-->
<!--        <label for="title">Title</label>-->
<!--        <br>-->
<!--        <input type="text" id="title" placeholder="title" name="title">-->
<!--    </div>-->
<!--    <div style="margin-top: 20px">-->
<!--        <label for="content">Content</label>-->
<!--        <br>-->
<!--        <textarea name="content" id="content" placeholder="content" cols="50" rows="4"></textarea>-->
<!--    </div>-->

    {{form.as_p}}

    <div style="margin-top: 20px">
        <input type="submit" value="Add new">
    </div>

</form>
    {% endif %}



{% endblock %}

templates/article/delete.html
{% extends 'base.html' %}

{% block title %} delete article {% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>
    siz <b>{{object.title}}</b>ni o'chirmoqchimisiz?
  </p>
  <a href="{% url 'article:list'%}">
    <button class="btn" style="color: green">yoq</button>
  </a>
  <button class="btn" type="submit" style="color: red">ha</button>
</form>


{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}

{% block title %}{{object.title}}{% endblock %}


{% block content %}

<h1>{{object.title}}</h1>
{% if object.image %}
<div>
    <img class="rasm" src="{{ object.image.url }}" alt="">
</div>
{% endif %}
<p>{{object.content}}</p>

<div>
 <code>
     {{object.created_date}}
 </code>

</div>
    <span>last edit: <i>{{object.modified_date}}</i></span>
 <div>
<!--        <button type="submit" class="btn">Edit</button>-->
     <a href="{% url 'article:edit' object.slug %}" class="btn">Edit</a>

 </div>

{% endblock %}

templates/article/edit.html
{% extends 'base.html' %}

{% block title %}Edit Article{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <button type="submit" class="btn" style="color: green">Edit</button>
    </div>
</form>

{% endblock %}

templates/article/index.html
{% extends "base.html" %}


{% block title %} Article {% endblock %}

{% block content %}
<!--<div>-->
<!--    <a href="{% url 'article:new_index' %}"><button type="submit" style="color: green" class="btn">New Edit</button></a>-->
<!--</div>-->
<div>
<form action="{% url 'article:list' %}">
    <input class="search" type="search" name="q" placeholder="search...">
    <input style="color: green" type="submit" value="search">
</form>
</div>
<div>
    <ol class="article_list">
        {% for object in object_list %}
        <li>
            <a href="{% url 'article:detail' object.slug%}"><button type="submit" style="color: green">{{object.title}}({{object.id}})</button></a>
            <a href="{% url 'article:edit' object.slug%}"><button type="submit" style="color: blue">Edit</button></a>
            <a href="{% url 'article:delete' object.slug%}"><button type="submit" style="color: red">Delete</button></a>
        </li>
        {% endfor %}
    </ol>
</div>
<div>
    <a href="{% url 'article:create' %}"><button type="submit" style="color: green" class="btn">add new article</button></a>
    <br>
</div>
<!--<div>-->
<!--    <br>-->
<!--    <a href="{% url 'article:newcreate' %}"><button type="submit" style="color: green" class="btn">New Create</button></a>-->
<!--</div>-->

{% endblock %}

templates/article/newedit.html
{% extends 'base.html' %}

{% block title %} Article {% endblock %}

{% block content %}

<div>
  <ol>
    {% for object in object_list %}
    <li>
      <a href="{% url 'article:detail' object.slug%}" class="btn">{{object.title}}</a>
    </li>
    {% endfor %}
  </ol>
</div>

{% endblock %}